export const Routes = {
  HOME: { path: "/" },
  REGISTRATION: { path: "/app/login/registration" },
  SIGNIN: { path: "/app/login/signin" },
  PROFILE: { path: "/app/profile" },
  FEED: { path: "/app/profile/feed" },
  CHAT: { path: "/app/profile/chats" },
  POST: { path: "/app/profile/post/:id" },
  HEADER: { path: "/app/header" },
  FOOTER: { path: "/app/footer" },
  Notfound: { path: "/404" },
  FORGETPASSWORD: { path: "/app/login/forgetpassword" },
  ACCOUNT_ACTIVATION: { path: "/account-activation/:token" },
  ABOUTME: { path: "/app/profile/aboutme" },
  COMMENTS: { path: "/app/Feed/comments" },
};
